name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        env:
          TELE_API_ID: ${{ secrets.TELE_API_ID }}
          TELE_API_HASH: ${{ secrets.TELE_API_HASH }}
          GROUP_A_ID: ${{ secrets.GROUP_A_ID }}
          GROUP_B_ID: ${{ secrets.GROUP_B_ID }}
        run: |
          echo "TELE_API_ID=${TELE_API_ID}" > .env
          echo "TELE_API_HASH=${TELE_API_HASH}" >> .env
          echo "GROUP_A_ID=${GROUP_A_ID}" >> .env
          echo "GROUP_B_ID=${GROUP_B_ID}" >> .env
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Check .env file
        run: |
          ls -l .env

      - name: Check folder
        run: |
          ls -la

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
            docker stop ${{ secrets.DOCKER_IMAGE_NAME }} || true
            docker rm ${{ secrets.DOCKER_IMAGE_NAME }} || true
            docker run -d --env-file /app/.env ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
